"use client";

import { useState, type FormEvent } from "react";
import { motion } from "framer-motion";
import { useRouter } from "next/navigation";
import {
  AlertCircle,
  CheckCircle,
  Globe,
  KeyRound,
  Loader2,
  Lock,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Smartphone,
  type LucideIcon,
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/supabase/client";
import {
  useGetMfaFactorsQuery,
  useGetSecuritySettingsQuery,
  useUnenrollMfaFactorMutation,
  useUpdateLockdownLevelMutation,
  useUpdateUserPasswordMutation,
} from "@/store/api/adminApi";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useConfirm } from "@/components/providers/ConfirmDialogProvider";
import { cn, getErrorMessage } from "@/lib/utils";

const LOCKDOWN_LEVELS: {
  level: number;
  icon: LucideIcon;
  title: string;
  titleClass?: string;
  description: string;
  activeClass: string;
  idleClass: string;
  activeIconClass: string;
}[] = [
  {
    level: 0,
    icon: Globe,
    title: "Level 0: Normal",
    description: "Public site is live.",
    activeClass: "border-chart-2 bg-chart-2/10 shadow-sm",
    idleClass:
      "border-border bg-background hover:border-chart-2/50 hover:bg-chart-2/5",
    activeIconClass: "text-chart-2",
  },
  {
    level: 1,
    icon: Lock,
    title: "Level 1: Maintenance",
    description: "Public site hidden. Admin accessible.",
    activeClass: "border-chart-3 bg-chart-3/10 shadow-sm",
    idleClass:
      "border-border bg-background hover:border-chart-3/50 hover:bg-chart-3/5",
    activeIconClass: "text-chart-3",
  },
  {
    level: 2,
    icon: Siren,
    title: "Level 2: Lockdown",
    titleClass: "text-destructive",
    description: "API Read-Only. No edits allowed.",
    activeClass: "border-destructive bg-destructive/20 shadow-sm",
    idleClass:
      "border-border bg-background hover:border-destructive/50 hover:bg-destructive/5",
    activeIconClass: "text-destructive",
  },
];

const BEST_PRACTICES = [
  "Keep your authenticator app secure and backed up (e.g. Authy cloud backup).",
  "Do not share your password or MFA codes with anyone.",
  "Use a strong, unique password generated by a password manager.",
  "Log out when you finish managing your site on shared devices.",
];

export default function SecurityPage() {
  const confirm = useConfirm();

  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [passwordError, setPasswordError] = useState("");
  const router = useRouter();

  const { data: security } = useGetSecuritySettingsQuery();
  const [updateLockdown, { isLoading: isLocking }] =
    useUpdateLockdownLevelMutation();

  const handleLockdown = async (level: number) => {
    const messages = [
      "Switch to Normal Mode? Site will be public.",
      "Switch to Maintenance Mode? Public site will be inaccessible.",
      "ACTIVATE LOCKDOWN? This is an emergency state.",
    ];
    const isConfirmed = await confirm({
      title: "Confirm Security Level Change",
      description: messages[level],
      variant: level === 2 ? "destructive" : "default",
      confirmText: "Yes, Change Level",
    });

    if (!isConfirmed) return;

    try {
      await updateLockdown(level).unwrap();
      toast.success(`Security Level set to ${level}`);
    } catch {
      toast.error("Failed to change security level");
    }
  };

  const level = security?.lockdown_level || 0;

  const {
    data: factors = [],
    isLoading: isLoadingFactors,
    error: factorsError,
  } = useGetMfaFactorsQuery();
  const [unenrollFactor, { isLoading: isUnenrolling }] =
    useUnenrollMfaFactorMutation();
  const [updatePassword, { isLoading: isUpdatingPassword }] =
    useUpdateUserPasswordMutation();

  const handleUnenroll = async (factorId: string) => {
    if (!supabase) return;
    const isConfirmed = await confirm({
      title: "Remove 2FA Method?",
      description:
        "Removing your only 2FA method may lock you out until you set it up again upon next login.",
      variant: "destructive",
      confirmText: "Remove",
    });

    if (!isConfirmed) return;
    try {
      await unenrollFactor(factorId).unwrap();
      toast.success("MFA method removed successfully.");
      const { data: aalData } =
        await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
      if (aalData?.currentLevel !== "aal2") {
        router.push("/admin/login");
      }
    } catch (err: unknown) {
      toast.error("Failed to unenroll MFA", {
        description: getErrorMessage(err),
      });
    }
  };

  const mfaEnabled = factors.some((f) => f.status === "verified");

  const handlePasswordChange = async (e: FormEvent) => {
    e.preventDefault();
    setPasswordError("");
    if (newPassword.length < 6) {
      setPasswordError("Password must be at least 6 characters long.");
      return;
    }
    if (newPassword !== confirmPassword) {
      setPasswordError("Passwords do not match.");
      return;
    }
    try {
      await updatePassword(newPassword).unwrap();
      toast.success("Password updated successfully!");
      setNewPassword("");
      setConfirmPassword("");
    } catch (err: unknown) {
      const msg = getErrorMessage(err);
      setPasswordError("Failed to update password: " + msg);
      toast.error("Password Update Failed", { description: msg });
    }
  };

  const isLoading = isLoadingFactors || isUnenrolling;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="mx-auto max-w-4xl space-y-8 pb-20 md:pb-0"
    >
      <div className="flex flex-col gap-2">
        <h2 className="font-heading text-2xl font-bold">Security Settings</h2>
        <p className="text-sm text-muted-foreground">
          Manage your account security and two-factor authentication.
        </p>
      </div>

      {!!factorsError && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            {factorsError &&
            typeof factorsError === "object" &&
            "message" in factorsError
              ? String((factorsError as { message: unknown }).message)
              : "Failed to load MFA status"}
          </AlertDescription>
        </Alert>
      )}

      <Card>
        <CardHeader className="pb-3">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
            <div className="flex flex-1 items-center gap-4">
              <div className="shrink-0">
                {mfaEnabled ? (
                  <ShieldCheck className="h-10 w-10 text-chart-2" />
                ) : (
                  <ShieldAlert className="h-10 w-10 text-chart-3" />
                )}
              </div>
              <div>
                <CardTitle className="text-lg">
                  Two-Factor Authentication (2FA)
                </CardTitle>
                <CardDescription className="mt-1">
                  {mfaEnabled
                    ? "Your account is secured with an additional layer of verification."
                    : "Add an extra layer of security to your account."}
                </CardDescription>
              </div>
            </div>
            <Badge
              variant={mfaEnabled ? "default" : "secondary"}
              className={cn(
                "mt-2 w-fit sm:mt-0",
                mfaEnabled ? "bg-chart-2/15 text-chart-2" : "",
              )}
            >
              {mfaEnabled ? "Enabled" : "Disabled"}
            </Badge>
          </div>
        </CardHeader>
        <CardContent>
          {!mfaEnabled && !isLoading && (
            <div className="rounded-lg border bg-secondary/30 p-6 text-center">
              <h3 className="font-semibold">2FA is not active</h3>
              <p className="mb-4 mt-1 text-sm text-muted-foreground">
                Protect your account from unauthorized access.
              </p>
              <Button
                onClick={() => router.push("/admin/setup-mfa")}
                className="w-full sm:w-auto"
              >
                <Smartphone className="mr-2 size-4" /> Enable 2FA Now
              </Button>
            </div>
          )}
          {mfaEnabled && factors.length > 0 && (
            <>
              <h4 className="mb-2 text-sm font-semibold">
                Registered Authenticators
              </h4>
              <div className="overflow-hidden rounded-md border">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead className="text-right">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {factors.map((factor) => (
                      <TableRow key={factor.id}>
                        <TableCell className="font-medium">
                          {factor.friendly_name || `Authenticator`}
                        </TableCell>
                        <TableCell>
                          <Badge
                            variant={
                              factor.status === "verified"
                                ? "default"
                                : "secondary"
                            }
                          >
                            {factor.status}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right">
                          <Button
                            onClick={() => handleUnenroll(factor.id)}
                            variant="destructive"
                            size="sm"
                            disabled={isLoading}
                          >
                            Remove
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </>
          )}
        </CardContent>
        {mfaEnabled && (
          <CardFooter className="border-t bg-muted/5 pt-4">
            <Button
              variant="outline"
              size="sm"
              onClick={() => router.push("/admin/setup-mfa")}
              disabled={isLoading}
              className="w-full sm:w-auto"
            >
              Add Another Method
            </Button>
          </CardFooter>
        )}
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <KeyRound className="size-5 text-primary" /> Change Password
          </CardTitle>
          <CardDescription>
            Update your login password. You will be logged out from other
            sessions.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handlePasswordChange} className="max-w-md space-y-4">
            <div>
              <Label htmlFor="new-password">New Password</Label>
              <Input
                id="new-password"
                type="password"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                required
                minLength={6}
                className="mt-1.5"
              />
            </div>
            <div>
              <Label htmlFor="confirm-password">Confirm New Password</Label>
              <Input
                id="confirm-password"
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
                minLength={6}
                className="mt-1.5"
              />
            </div>
            {passwordError && (
              <p className="rounded bg-destructive/10 p-2 text-sm font-medium text-destructive">
                {passwordError}
              </p>
            )}
            <Button
              type="submit"
              disabled={isUpdatingPassword || !newPassword || !confirmPassword}
              className="w-full sm:w-auto"
            >
              {isUpdatingPassword ? (
                <>
                  <Loader2 className="mr-2 size-4 animate-spin" /> Updating...
                </>
              ) : (
                "Update Password"
              )}
            </Button>
          </form>
        </CardContent>
      </Card>

      <Card className="border-destructive/30 bg-destructive/5">
        <CardHeader>
          <div className="flex flex-col items-start gap-4 sm:flex-row sm:items-center">
            <div className="shrink-0 animate-pulse rounded-full bg-destructive/10 p-3">
              <Siren className="h-8 w-8 text-destructive" />
            </div>
            <div>
              <CardTitle className="text-destructive">
                Emergency Protocol
              </CardTitle>
              <CardDescription>
                Control global access to your portfolio in case of emergency.
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {LOCKDOWN_LEVELS.map((option) => (
            <button
              key={option.level}
              onClick={() => handleLockdown(option.level)}
              disabled={isLocking}
              className={cn(
                "flex h-32 flex-col items-center justify-center rounded-xl border-2 p-4 transition-all duration-200",
                level === option.level ? option.activeClass : option.idleClass,
              )}
            >
              <option.icon
                className={cn(
                  "mb-2 size-8",
                  level === option.level
                    ? option.activeIconClass
                    : "text-muted-foreground",
                )}
              />
              <span className={cn("font-bold", option.titleClass)}>
                {option.title}
              </span>
              <span className="mt-1 text-center text-xs text-muted-foreground">
                {option.description}
              </span>
            </button>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Security Best Practices</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3 text-sm text-muted-foreground">
            {BEST_PRACTICES.map((tip) => (
              <li key={tip} className="flex items-start">
                <CheckCircle className="mr-3 mt-0.5 size-4 shrink-0 text-primary" />
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </motion.div>
  );
}
